import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import YAML from "yaml";
import { parseFuncSchema } from "./schemaParser.js";
import { filterSubset } from "./subset.js";
import { makeNodeClassName } from "./naming.js";
import { renderNodeDefinition } from "./renderer.js";
import type { GeneratorConfig, TorchFunction } from "./types.js";

interface RawNativeFunction {
  func: string;
  tags?: string[] | string;
  variants?: string[] | string;
}

async function readSource(source: string): Promise<string> {
  if (source.startsWith("http://") || source.startsWith("https://")) {
    const response = await fetch(source);
    if (!response.ok) {
      throw new Error(`Failed to fetch source: ${response.status} ${response.statusText}`);
    }
    return response.text();
  }

  return readFile(source, "utf-8");
}

function asStringArray(input: string[] | string | undefined): string[] {
  if (!input) return [];
  return Array.isArray(input)
    ? input
    : input
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
}

function parseRawNativeFunctions(yamlText: string): TorchFunction[] {
  const doc = YAML.parse(yamlText) as RawNativeFunction[];
  if (!Array.isArray(doc)) {
    throw new Error("native_functions.yaml does not parse to an array");
  }

  const result: TorchFunction[] = [];
  for (const item of doc) {
    if (!item || typeof item.func !== "string") continue;
    const tags = asStringArray(item.tags);
    const variants = asStringArray(item.variants);
    result.push(parseFuncSchema(item.func, tags, variants));
  }
  return result;
}

function renderFileHeader(): string {
  return `// Auto-generated by tora transpiler.\n// Do not edit manually.\n\n#include "Properties.hpp"\n#include <torch/torch.h>\n#include <optional>\n#include <tuple>\n#include <stdexcept>\n\n`;
}

function renderRegistrationManifest(classNames: string[]): string {
  const includes = classNames
    .map((className) => `#include "nodes/${className}.hpp"`)
    .join("\n");

  const registrations = classNames
    .map((className) => `    callback.template operator()<${className}>();`)
    .join("\n");

  return `// Auto-generated by tora transpiler.
// Do not edit manually.

#pragma once

${includes}

namespace GFExtensionsPyTorchGenerated {

template <typename TCallback>
void ForEachProcessor(TCallback&& callback)
{
${registrations}
}

} // namespace GFExtensionsPyTorchGenerated
`;
}

export async function runGenerator(config: GeneratorConfig): Promise<void> {
  const yamlText = await readSource(config.source);
  const parsed = parseRawNativeFunctions(yamlText);
  const filtered = await filterSubset(
    parsed,
    config.subset,
    config.includeNameRegex,
    config.allowlistPath
  );

  await rm(config.outDir, { recursive: true, force: true });
  await mkdir(config.outDir, { recursive: true });
  const nodesDir = path.join(config.outDir, "nodes");
  await mkdir(nodesDir, { recursive: true });

  const manifestLines: string[] = [];
  const classNames: string[] = [];

  for (const fn of filtered) {
    const className = makeNodeClassName(fn);
    const fileName = `${className}.hpp`;
    const filePath = path.join(nodesDir, fileName);
    const content = renderFileHeader() + renderNodeDefinition(fn);
    await writeFile(filePath, content, "utf-8");
    manifestLines.push(`${className}: ${fn.rawFunc}`);
    classNames.push(className);
  }

  const registrationManifest = renderRegistrationManifest(classNames);
  await writeFile(path.join(config.outDir, "GeneratedProcessorsManifest.hpp"), registrationManifest, "utf-8");

  const manifest = [
    "# Generated Node Manifest",
    `source: ${config.source}`,
    `count: ${filtered.length}`,
    "",
    ...manifestLines
  ].join("\n");

  await writeFile(path.join(config.outDir, "manifest.txt"), manifest, "utf-8");
}